In [1]:
#Regression
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
#Classifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report,roc_auc_score,log_loss


In [2]:
R=pd.read_csv('Tourism.csv')
R.nunique()

TransactionId                  52922
UserId                         33526
VisitYear                         10
VisitMonth                        12
VisitMode_x                        5
AttractionId                      30
Rating                             5
ContinentId_x                      5
RegionId_x                        22
CountryId_x                      153
CityId                          5545
CityName                        5545
CountryId_y                      151
Country                          151
RegionId_y                        22
Region                            22
ContinentId_y                      6
Continent                          6
VisitModeId                        5
VisitMode_y                        5
AttractionCityId                   3
AttractionTypeId                  17
Attraction                        30
AttractionAddress                 25
AttractionType                    17
CityName_Frequency               140
CityId_Frequency                 140
C

# regression

In [3]:
from sklearn.preprocessing import LabelEncoder
R=pd.read_csv('Tourism.csv')

In [4]:
R=pd.read_csv('Tourism.csv')

Features=R[['Attraction_Frequency','AttractionAddress_Frequency','Country_Frequency']]
# Features=R[['Region_Frequency','Country_Frequency','CityId_Frequency','CityId','RegionId_y','CountryId_y','VisitYear','VisitMonth','VisitMode_y_LB_EC','Attraction_Frequency','AttractionTypeId','AttractionAddress_Frequency']]
Target=R['Rating']

Features_train,Features_test,Target_train,Target_test=train_test_split(Features,Target,test_size=0.2,random_state=42)

RF_Model=RandomForestRegressor(n_estimators=100,random_state=42)
RF_Model.fit(Features_train,Target_train)

Target_predict=RF_Model.predict(Features_test)

print(f"The Mean Absolute Error: {mean_absolute_error(Target_test,Target_predict)}")
print(f"The Mean Square Error : {mean_squared_error(Target_test,Target_predict)}")
print(f"The Root Mean Square Error: {np.sqrt(mean_absolute_error(Target_test,Target_predict))}")
print(f"The R2 Score : {r2_score(Target_test,Target_predict):.4f}")

The Mean Absolute Error: 0.7293080050674965
The Mean Square Error : 0.867365895948494
The Root Mean Square Error: 0.8539953191133406
The R2 Score : 0.0871


In [5]:
C=pd.read_csv('Tourism.csv')
Features=C[['AttractionId','TransactionId','VisitModeId','AttractionCityId']]
Target=C['VisitMode_y_LB_EC']

Features_train,Features_test,Target_train,Target_test=train_test_split(Features,Target,test_size=0.2,random_state=42)

rf = RandomForestClassifier(n_estimators=50, random_state=42)
rf.fit(Features_train,Target_train)

Target_predict=rf.predict(Features_test)

accuracy_scores=accuracy_score(Target_test,Target_predict)
print(f"\n The Accuracy Of Test : \n{accuracy_scores:.2f}")



 The Accuracy Of Test : 
1.00


In [6]:
cm = confusion_matrix(Target_test, Target_predict)
report = classification_report(Target_test, Target_predict)
probs = rf.predict_proba(Features_test)
roc_auc = roc_auc_score(Target_test, probs, multi_class='ovr', average='weighted')
logloss = log_loss(Target_test, probs)
 
print(f"\nLog Loss:\n {logloss:.2f}")
print(f"\nROC AUC Score: \n{roc_auc:.2f}")
print(f"\n Classification Report: \n{report}")
print(f"\n Confusion Matrix: \n{cm}")
print(f"\n The Accuracy Of Test : \n{accuracy_scores:.2f}")



Log Loss:
 0.00

ROC AUC Score: 
1.00

 Classification Report: 
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       135
           1       1.00      1.00      1.00      4337
           2       1.00      1.00      1.00      2995
           3       1.00      1.00      1.00      2190
           4       1.00      1.00      1.00       928

    accuracy                           1.00     10585
   macro avg       1.00      1.00      1.00     10585
weighted avg       1.00      1.00      1.00     10585


 Confusion Matrix: 
[[ 135    0    0    0    0]
 [   0 4337    0    0    0]
 [   0    0 2995    0    0]
 [   0    0    0 2190    0]
 [   0    0    0    0  928]]

 The Accuracy Of Test : 
1.00
